name: swot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets

  # Data
  - earthaccess
  - rioxarray
  - xarray
  - h5netcdf
  - cfgrib
  - geopandas
  - dask

  # Viz
  - hvplot
  - holoviews
  - geoviews
  - matplotlib
  - seaborn